

Vagrant.configure("2") do |config|

	#
  config.vm.box = "ubuntu_lammy64"


  config.vm.box_check_update = false



  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  #add Folder with sync folder
   config.vm.synced_folder "../data", "/vagrant_data"


  # Устанавливаем apache2
   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2
   SHELL
end
